# Generated by Django 3.1.3 on 2020-12-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hikerName', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=30)),
                ('length', models.FloatField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
